#!/bin/bash

echo "[alima-monorepo] Linting for syntax errors and undefined names."
SYN_ERR=$(poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=*/*/.venv/,projects/api/*)
if [ $? -eq 0 ]
then
    echo "[alima-monorepo] Num Errors: $SYN_ERR"
    exit 0
else
    echo "[alima-monorepo] Error: $SYN_ERR" >&2
    exit 1
fi